# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sky_task' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sky_task
  pod 'Alamofire',  '~> 4.5'
  pod 'RxSwift',    '~> 4.0'
  pod 'SwiftyJSON'

  target 'sky_taskUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking', '~> 4.0'
    pod 'RxTest',     '~> 4.0'
  end

end
